name: Lint, Package, and Push Helm Chart

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: charming-study-382702
  GAR_LOCATION: us-central1
  REPOSITORY: for-hello-docker
  IMAGE: proj-image
  CHART_NAME: K8S-HELM
  CHART_VERSION: 0.1.0

jobs:
  build-and-push:
    name: Lint, Package, and Push Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.6.3"

      - name: Lint Helm Chart
        run: helm lint $CHART_NAME

      - name: Package Helm Chart
        run: helm package $CHART_NAME --version $CHART_VERSION --destination charts/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROJ }}
          token_format: "access_token"

      - name: Create Google Cloud Storage bucket
        run: gsutil mb gs://$GAR_LOCATION-docker.pkg.dev

      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker --quiet

      - name: Push Helm Chart to GAR
        run: |
          gsutil cp charts/*.tgz gs://$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$CHART_NAME-$CHART_VERSION.tgz
