name: Lint, Package, and Push Helm Chart

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: charming-study-382702
  GAR_LOCATION: us-central1
  REPOSITORY: for-hello-chart
  IMAGE: proj-image

jobs:
  build-and-push:
    name: Lint, Package, and Push Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.6.3"

      - name: Lint Helm Chart
        run: helm lint $CHART_NAME

      - name: Package Helm Chart
        run: helm package $CHART_NAME --version $CHART_VERSION --destination charts/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROJ }}
          token_format: "access_token"

      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build --tag $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA .

      - name: Authenticate to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ secrets.GCP_TOKEN }}

      - name: Push Docker image
        run: |
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Helm Chart Manifests
        run: trivy --quiet --exit-code 0 --severity HIGH,CRITICAL --no-progress charts/*.tgz
